### ISSUE TITLE
[Feature Request] Increasing the width of the block of documentation

### ISSUE THREAD

**Issue by ExPande** [getinsomnia/insomnia#1519]
- Insomnia Version: 6.5.3
- Operating System: Windows 10

I propose to increase the width of the block of documentation.
![Screenshot_1](https://user-images.githubusercontent.com/15219302/58239684-2ac73780-7d52-11e9-8655-430b90070893.png)
![Screenshot_2](https://user-images.githubusercontent.com/15219302/58239685-2ac73780-7d52-11e9-9447-9c8ecb46d67f.png)

My proposed solution is to change the CSS right

```css
.markdown-preview__content {
    max-width: 860px; //(present value: 36em)
    margin-right: auto;
}
```
