### ISSUE TITLE
Various Kong for Kubernetes config generation bugs

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2102]
- [x] Name derived from `x-kubernetes-ingress-metadata` is not slugified
    <details>
    <summary>Example</summary>
    
    #### Source spec
    
    ```yaml
    openapi: 3.0.0
    info:
        x-kubernetes-ingress-metadata:
        name: Insomnia API
    servers:
        - url: http://api.insomnia.rest/v1
    paths:
    ```
    
    #### Current output
    
    ```yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
        name: Insomnia API
    spec:
        rules:
        - host: api.insomnia.rest
            http:
            paths:
                - path: /v1/.*
                backend:
                    serviceName: Insomnia API-s0
                    servicePort: 80
    ```
    
    #### Expected output
    ```yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
        name: insomnia-api
    spec:
        rules:
        - host: api.insomnia.rest
            http:
            paths:
                - path: /v1/.*
                backend:
                    serviceName: insomnia-api-s0
                    servicePort: 80
    ```
    </details>

- [x] If the server url is at root, the path rule generated is null
	<details>
	<summary>Example</summary>
	
	#### Source spec
	
	```yaml
	openapi: 3.0.0
	info:
	  title: Insomnia API
	servers:
	  - url: http://api.insomnia.rest/
	paths:
	```
	
	#### Current output
	
	```yaml
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	spec:
	  rules:
	    - host: api.insomnia.rest
	      http:
	        paths:
	          - path: null
	            backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	```
	
	#### Expected output
	```yaml
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	spec:
	  rules:
	    - host: api.insomnia.rest
	      http:
	        paths:
	          - backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	```
	</details>

- [x] All metadata objects on the Ingress documents for the following spec are identical; they should not be and should be as per the expected output
	<details>
	<Summary>Example</Summary>
	
	```yaml
	openapi: 3.0.0
	info:
	  x-kubernetes-ingress-metadata:
	    name: insomnia-api                          # Kubernetes Ingress document name
	    annotations:                                # Annotations to automatically apply
	      'example': 'example'
	x-kong-plugin-custom-global:                    # Global plugin to always be applied
	  name: custom-global
	  enabled: true
	  config:
	    key_in_body: false
	servers:
	  - url: http://one.insomnia.rest/v1
	  - url: http://two.insomnia.rest/v2
	    x-kong-plugin-custom-server:                # Server plugin to be applied to documents for this server
	      name: custom-server
	      enabled: true
	paths:
	  '/path':
	    post:
	      summary: Some functionality               # A path with no plugins on the path or operations in it
	  '/another-path':
	    get:
	      summary: Some functionality
	      x-kong-plugin-key-auth:                   # Operation plugin on GET /another-path
	        name: key-auth
	        enabled: true
	        config:
	          key_names: [api_key, apikey]
	          key_in_body: false
	          hide_credentials: true
	```
	</details>
	
	<details>
	<summary>Expected output</summary>

	```yaml
	apiVersion: configuration.konghq.com/v1
	kind: KongIngress
	metadata:
	  name: get-method                              # KongIngress due to GET /another-path containing a plugin
	route:
	  methods:
	    - get
	---
	apiVersion: configuration.konghq.com/v1
	kind: KongPlugin
	metadata:
	  name: add-custom-global-g0                    # KongPlugin due to plugin at OpenAPI object level
	plugin: custom-global
	config:
	  key_in_body: false
	---
	apiVersion: configuration.konghq.com/v1
	kind: KongPlugin
	metadata:
	  name: add-custom-server-s1                    # KongPlugin due to plugin on the second server
	plugin: custom-server
	---
	apiVersion: configuration.konghq.com/v1
	kind: KongPlugin
	metadata:
	  name: add-key-auth-m2                         # KongPlugin due to plugin on GET /another-path
	plugin: key-auth
	config:
	  key_names:
	    - api_key
	    - apikey
	  key_in_body: false
	  hide_credentials: true
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example                            # annotation from x-kong-ingress-metadata
	    konghq.com/plugins: add-custom-global-g0    # only global plugin
	spec:
	  rules:
	    - host: one.insomnia.rest
	      http:
	        paths:
	          - path: /v1/path
	            backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example
	    konghq.com/plugins: add-custom-global-g0, add-key-auth-m2   # global and operation plugin, no server or path
	    konghq.com/override: get-method             # restrict document to be for specified operation (due to plugin)
	spec:
	  rules:
	    - host: one.insomnia.rest
	      http:
	        paths:
	          - path: /v1/another
	            backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example
	    konghq.com/plugins: add-custom-global-g0, add-custom-server-s1    # global and server 1 plugin, no path or operation
	spec:
	  rules:
	    - host: two.insomnia.rest
	      http:
	        paths:
	          - path: /v2/path
	            backend:
	              serviceName: insomnia-api-s1
	              servicePort: 80
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example
	    konghq.com/plugins: add-custom-global-g0, add-custom-server-s1, add-key-auth-m2   # global, server 1, and operation plugin, no path
	    konghq.com/override: get-method             # restrict document to be for specified operation (due to plugin)
	spec:
	  rules:
	    - host: two.insomnia.rest
	      http:
	        paths:
	          - path: /v2/another
	            backend:
	              serviceName: insomnia-api-s1
	              servicePort: 80
	```
	</details>
