### ISSUE TITLE
Insomnia Designer does not tag generated declarative Kong config with tags in the spec

### ISSUE THREAD

**Issue by felderi** [getinsomnia/insomnia#2682]
**Describe the bug**
When writing a spec and leveraging tags, generating Kong configuration from the spec does not tag the configuration with the tags in the spec.  

This leads to a situation where teams working on different specs, generating declarative config and running deck to sync config could overwrite other teams configuration.  

**To Reproduce**
1. Use ID or inso with a spec with tags to generate a Kong declarative config.  
2. Notice the tags in the spec are not available in the Kong declarative config.  

**Expected behavior**
The generated Kong declarative config should show the tags in spec.   This will assure when running deck sync that only the appropriate objects are worked on.

**Comment by develohpanda** [comment]
**For example,** the following tag applied to a `x-kong-plugin` entity (although this behavior is exhibited by other entities as well):
```yaml
  x-kong-plugin-rate-limiting:
        enabled: true
        config:
          minute: 5
          limit_by: ip
          policy: local
        tags: 
        - custom_tag
```

Will generate the following declarative config (without a tag):
```yaml
        plugins:
          - name: mocking
            config:
              api_specification_filename: orders.yaml
          - name: rate-limiting
            config:
              minute: 5
              limit_by: ip
              policy: local
```
