### ISSUE TITLE
Insomnia Designer: how to I export my openAPI spec in a single standalone YAML file?

### ISSUE THREAD

**Issue by mxmlnglt** [getinsomnia/insomnia#2996]
I run Designer 2020.5.2 on macOS Big Sur 11.0.1

I managed to write a working spec but now I'm willing to send it to colleagues who are not working with Designer.
So I basically need to send them the YAML file.

I connected Insomnia Designer to a git repo (a GitLab one); this worked, but now I've got 2 files inside the `.insomnia` folder:
ApiSpec/spc_<some_random_hexa_id>.yml
Workspace/wrk_<another_random_hexa_id>.yml

But the 1st one is not a "pure" openAPI spec because it starts with:
```yaml
_id: spc_<the_random_hexa_id_above>
type: ApiSpec
parentId: wrk_<the_workspace_hexa_id_seen_above>
modified: <a_numeric_timestamp>
created:  <another_numeric_timestamp>
fileName: My API title + version
contents: >
 # and now goes the REAL content of my spec!
contentType: yaml
```
I can't send this "as is"?!!

I also tried the Preferences menu item > Data tab > "Export Data" button, and when checking "Current Document" I'm let choosing between the few API calls that were automatically generated in the main "Debug" tab (and if I uncheck ALL of them, I can't Export - button is greyed)

The only option I can resort on is a simple copy-paste, create a new file by hand and save it.
That's absurd?!
