### ISSUE TITLE
Kong configuration creates invalid plugin config for schema validation on query parameters

### ISSUE THREAD

**Issue by svenwal** [getinsomnia/insomnia#3083]
**Describe the bug**

When using the feature to create Kong-decK-YAML files (either in inso cli or in Insomnia Designer) there is the option to add the Request-Validator plugin to generate the JSON Schema automatically based on the OAS - see also https://www.npmjs.com/package/openapi-2-kong#request-validation-plugin

When having parameters as path this works fine, if you have a parameter in query than the generated JSON Schema definition is invalid and Kong is unable to import the plugin config

**To Reproduce**

1. Create an OAS with a path like this

```
 /delay:
    get:
      parameters:
        - in: query
          name: delay
          required: true
          schema:
            type: integer
            minimum: 0
            maximum: 10
          description: The delay in seconds
      x-kong-plugin-request-validator:
        enabled: true
```

2. Use the button in Insomia or inso cli like `inso generate config ./uuid-generator.yaml -o kong-uuid-generator.yaml` to generate a Kong decK config

3. try to import the generated YAML into Kong using decK

**Expected behavior**

The generated YAML should should look like

```
        plugins:
          - config:
              version: draft4
              parameter_schema:
                - in: query
                  explode: false
                  required: true
                  name: delay
                  schema: '{"type":"integer","minimum":0,"maximum":10}'
                  style: form
            enabled: true
```

but instead looks like 

```
        plugins:
          - config:
              version: draft4
              parameter_schema:
                - in: query
                  explode: false
                  required: true
                  name: delay
                  schema: '{"type":"integer","minimum":0,"maximum":10}'
                  style: simple
            enabled: true
```

**Notice the style entry (simple vs. form)**. 

According to the plugin config at https://github.com/Kong/kong-plugin-enterprise-request-validator/blob/42a59a81c598924ba07136f68573b9f05d9952f2/kong/plugins/request-validator/schema.lua#L35 you can see allowed values.

Expected would be either to always set a correct setting (like form for query) or better to somehow make it configurable as there are more options for query parameter than form.

**Desktop (please complete the following information):**
 - OS: mac OS Big Sur 11.2
 - Installation Method: Download DMG (Designer), npm install (inso cli)
 - App Version: latest as of today

**Additional context**

Raised by a prospect wanting to automate everything in CI/CD based on OAS from A-Z

**Comment by develohpanda** [comment]
I think this has been resolved and is in production on Insomnia v2021.4.1

Using the following spec:

```yaml
openapi: 3.0.1
info:
  version: 1.0.2
  title: Example spec
servers:
  - url: https://petstore.swagger.io/v2
paths:
  /delay:
    get:
      parameters:
        - in: query
          name: delay
          required: true
          schema:
            type: integer
            minimum: 0
            maximum: 10
          description: The delay in seconds
      x-kong-plugin-request-validator:
        enabled: true
```

The following Declarative config is generated (note the `plugins` entry matches the expected result)
```yaml
_format_version: "1.1"
services:
  - name: Example_spec
    protocol: https
    host: Example_spec
    port: 443
    path: /v2
    plugins: []
    routes:
      - tags:
          - OAS3_import
        name: Example_spec-delay-get
        methods:
          - GET
        paths:
          - /delay$
        strip_path: false
        plugins:
          - name: request-validator
            config:
              version: draft4
              parameter_schema:
                - in: query
                  explode: false
                  required: true
                  name: delay
                  schema: '{"type":"integer","minimum":0,"maximum":10}'
                  style: form
            tags:
              - OAS3_import
            enabled: true
    tags:
      - OAS3_import
upstreams:
  - name: Example_spec
    targets:
      - target: petstore.swagger.io:443
        tags:
          - OAS3_import
    tags:
      - OAS3_import

```
