### ISSUE TITLE
Open api importer support for oauth 2 security schemes

### ISSUE THREAD

**Issue by alisters** [getinsomnia/insomnia#3093]
Hi, 

I import our companies open api specs, which contain oauth 2 security schemes. I see that you've implemented basic auth importation, but not oauth2. 

I had a very quick look at the code here - https://github.com/Kong/insomnia/blob/e11be78ba817a37357204cab6e5264ce397c7bd6/packages/insomnia-importers/src/importers/openapi3.js#L274 

and a previous issue here
https://github.com/Kong/insomnia/issues/1698

It looks like returning the authentication object for oauth2 would be possible, and like basic auth, could be made to create and reference environment variables like access token url, authorizaton url, client id, client secret etc. 

Is there significant additional complexity that i'm missing ? If not i can put together an MR - but i thought considering only basic auth was done previously that i should check first

**Comment by sebastianjonasson** [comment]
It seems like you are referencing an old version of the file. Support for importing oauth2 security schemes from an oas-file should already be included. Got merged in PR https://github.com/Kong/insomnia/pull/2184.

**Comment by martin-thoma** [comment]
I have endpoints marked with

```
      security:
      - oauth2:
        - someobject:read
 ```

and the securitySchemes:

```
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://localhost/api/oauth/token
          scopes:
            someobject:read: someobject reads operations
```

in my `OpenAPI3-spec.yaml`. After importing the yaml into insomnia 2021.4.1, Insonmia still requires me to select the authentication + client credentials + token URL manually.
