### ISSUE TITLE
Plugin extension 'enabled' not respected in OpenAPI config

### ISSUE THREAD

**Issue by rossmcdonald** [getinsomnia/insomnia#3153]
## To Reproduce

Add a plugin extension similar to the following to an OAI spec:

```yaml
      x-kong-plugin-cors:
        enabled: false
        config:
          origins: 
            - "*"
          credentials: false
          preflight_continue: false
```

Then run `inso generate config path/to/file.yml`. Type is not important, as both output formats have the same issue.

## Expected

Since `enabled: false` is present, it would either be present and disabled or not present in the generated output at all.

## Actual

The same output is generated, regardless of whether `enabled` is `true` or `false`.

**Comment by HarryET** [comment]
Hey 👋🏼, I was just looking into fixing this. I think I have fixed it with my PR #4235. This is my first contribution to insomnia/related packages so let me know if I've done something wrong.

**Comment by develohpanda** [comment]
Hi @HarryET, thanks for the PR! 

> Since `enabled: false` is present, it would either be present and disabled or not present in the generated output at all.

@Tieske, do you have an opinion on which of these we should go with - present and disabled, vs not present at all?

**Comment by Tieske** [comment]
since this is a valid property for Kong, I think it should be valid to set it in the OAS doc as well. Which then results in the plugin being added to the generated config, with the property set to false.

My 2cts

**Comment by Tieske** [comment]
since this is a valid property for Kong, I think it should be valid to set it in the OAS doc as well. Which then results in the plugin being added to the generated config, with the property set to false.

My 2cts

**Comment by develohpanda** [comment]
That sounds good to me too. @HarryET could you please update your PR to still generate the plugin but set the enabled property to false? Once that's done I'll go ahead and review 😊

**Comment by HarryET** [comment]
Okay! Have you got a file I could use to test? @develohpanda

**Comment by develohpanda** [comment]
Unfortunately I'm not at a computer right now but I can send one through in the next 24h!

**Comment by HarryET** [comment]
> Unfortunately I'm not at a computer right now but I can send one through in the next 24h!

That would be awesome, thanks. I'll try make one myself but if that fails ill wait for yours :)

**Comment by develohpanda** [comment]
Hmm, so I've been preparing an input/output example @HarryET, but I think this has actually been fixed somehow already 🤔 

<details>
<summary>Using this input</summary>

```yaml
openapi: 3.0.1
info:
  description: Description
  version: 1.0.0
  title: API
servers:
  - url: 'https://api.insomnia.rest'
x-kong-plugin-cors:
  enabled: false
  config:
    origins: 
      - "*"
    credentials: false
    preflight_continue: false
paths:
  /path:
    x-kong-plugin-oidc:
      name: oidc
      enabled: false
      config:
        key_names: [api_key, apikey]
        key_in_body: false
        hide_credentials: true
    get:
      description: 'test'
      responses:
        '200':
          description: OK
```
</details>

<details>
<summary>I currently get this output</summary>

```yaml
_format_version: "1.1"
services:
  - name: API
    protocol: https
    host: API.upstream
    port: 443
    path: /
    plugins:
      - enabled: false
        config:
          origins:
            - "*"
          credentials: false
          preflight_continue: false
        name: cors
        tags:
          - OAS3_import
    routes:
      - tags:
          - OAS3_import
        name: API-path-get
        methods:
          - GET
        paths:
          - /path$
        strip_path: false
        plugins:
          - name: oidc
            enabled: false
            config:
              key_names:
                - api_key
                - apikey
              key_in_body: false
              hide_credentials: true
            tags:
              - OAS3_import
    tags:
      - OAS3_import
upstreams:
  - name: API.upstream
    targets:
      - target: api.insomnia.rest:443
        tags:
          - OAS3_import
    tags:
      - OAS3_import
```

</details>

Showing that the plugin exists in the final output, but is marked as disabled as per the input OpenAPI spec. Unless I'm mistaken I think we can close this issue and PR!

I really appreciate the time you put into this and I'm sorry we didn't follow-up and close this issue when it was resolved :( If you'd like to find another issue, tag me and I'll double check before you start. Alternatively I can find and suggest a good one to start with!
