### ISSUE TITLE
OAuth2 with OAS3 redirect_uri is invalid

### ISSUE THREAD

**Issue by PierreAdam** [getinsomnia/insomnia#3780]
**Describe the bug**
When an OAS3 is created as a Document and has an oauth2 type of authentication, the login is not working on some SSO due to the redirect_uri parameter. This is due to the redirect_url being a file:///... . 
I first thought that it was a problem with our Keycloak SSO but after investigating with RedHat, I found out that it's a bad practice to redirect to a file and that Keycloak just does not accept it.

Here are two snapshot from our front-end server : 

Here is a working request:
```
GET /auth/realms/angular-test/protocol/openid-connect/auth?response_type=code&client_id=angular-app&redirect_uri=www.google.fr
```

And here is the non working request from insomnia:
```
GET /auth/realms/angular-test/protocol/openid-connect/auth?response_type=code&client_id=angular-app&redirect_uri=file%3A%2F%2F%2Foauth2-redirect.html&state=RnJpIEp1biAyNSAyMDIxIDE4OjQ4OjQxIEdNVCswMjAwIChDZW50cmFsIEV1cm9wZWFuIFN1bW1lciBUaW1lKQ%3D%3
```

**To Reproduce**
Create a Document with the following part 
```yaml
components:
  securitySchemes:
    oauth2-server:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/auth'
          tokenUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/token'
          refreshUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/token'
          scopes: { }
```

**Expected behavior**
The redirect_uri should redirect to something else than a file:// for example, http://127.0.0.1:1234/... 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Windows Installer
 - App Version: 2021.4.0

**Additional context**
There are some reasons why the file:// is not accepted by some SSO. According to some ticket on the RedHat tracker, it doesn't make sense because browser will refuse the redirect anyway. So it's really an edge-case to do that and is only working in specific cases. So I guess for developement / compatibility it would be nice to have a something more generic.

PS : If you want a clientId on our SSO for testing, feel free to reach out to me. But it's really as simple as running a keycloak instance and trying to log on it.
PS2 : When you go through the authentication process with the oauth2 on the collection, it's working perfectly. I think from what I gathered of the swagger documentation that there is a configuration called `oauth2RedirectUrl` that can be set.
