### ISSUE TITLE
OAuth2 with OAS3 scopes are not transmitted correctly

### ISSUE THREAD

**Issue by PierreAdam** [getinsomnia/insomnia#3781]
**Describe the bug**
When specifying some scopes using an OAS3 document, when you select them on the popup where you select your clientId, instead of sending the scope to the SSO, it's sending the "index". 
If you have the scopes : 
- api_user_read
- api_user_write

If you select both scopes, the URL being called will contain `&scopes=0%201` without the URL encoding `scope=0 1`.
This only happen if you respect the syntaxe specified by swagger https://swagger.io/docs/specification/authentication/oauth2/

**To Reproduce**
```yaml
components:
  securitySchemes:
    oauth2-server:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/auth'
          tokenUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/token'
          refreshUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/token'
          scopes:
            - openid
            - profile
```
This will produce an array with openid and profile as value but in insomnia, it's the key that is being sent.

**Expected behavior**
The scopes `openid` and `profile` should be sent to the SSO

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installation Method: Windows Installer
 - App Version: 2021.4.0

**Additional context**
A work around right now it to do the following:
``` yaml
  securitySchemes:
    oauth2-server:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/auth'
          tokenUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/token'
          refreshUrl: 'https://sso.payin.tech/auth/realms/angular-test/protocol/openid-connect/token'
          scopes:
            openid: 'The open ID scope'
            profile: 'The profile scope'
```
