### ISSUE TITLE
`--tags` option in insomnia-inso does not work when `--type kubernetes` is used

### ISSUE THREAD

**Issue by msmith93** [getinsomnia/insomnia#3807]
**Describe the bug**
The `--tags` option only works when `--type declarative` is used. This is probably because no Kong K8S Custom Resources support adding tags to entities currently. The README should be update to clarify that `--tags` only works with the declarative output. 

**To Reproduce**
1. inso generate config <file> --tags mytag --output out.yaml --type declarative
a. Produces YAML with select_tags
2. inso generate config <file> --tags mytag --output out.yaml --type kubernetes
a. No trace of "mytag" in resulting YAML

**Expected behavior**
Either:
* Resulting k8s resource YAMLs contain the select tag
or
* README is updated to clarify that `--tags` only works with `--type declarative`

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Installation Method: npm
 - App Version 2.3.0

**Comment by filfreire** [comment]
Hi @msmith93, thank you for reporting this issue!

I can reproduce this locally using latest inso (3.0.0) and this [example repo](https://github.com/filfreire/dino-park-insomnia).

Running `inso generate config --tags mytags --output out.yaml --type declarative`, I got:
```
_format_version: "1.1"
services:
  - name: Dino_Park
    protocol: https
    host: mockbin.org
    port: 443
    path: /request/v1
    plugins: []
    routes:
      - tags:
          - OAS3_import
          - mytags
        name: Dino_Park-listDinosaurs
        methods:
          - GET
        paths:
          - /dinosaurs$
        strip_path: false
      - tags:
          - OAS3_import
          - mytags
        name: Dino_Park-createDinosaur
        methods:
          - POST
        paths:
          - /dinosaurs$
        strip_path: false
      - tags:
          - OAS3_import
          - mytags
        name: Dino_Park-securityFences
        methods:
          - POST
        paths:
          - /security/fences$
        strip_path: false
    tags:
      - OAS3_import
      - mytags

```

Running `inso generate config --tags mytags --output out.yaml --type kubernetes`, I got::
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dino-park-0
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: mockbin.org
      http:
        paths:
          - backend:
              service:
                name: dino-park-service-0
                port:
                  number: 80
            path: /request/v1/.*
            pathType: ImplementationSpecific
```
