### ISSUE TITLE
Path has $ appended when it does not contain a variable

### ISSUE THREAD

**Issue by AleksaKolarski** [getinsomnia/insomnia#4052]
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2.3.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

npm

### Expected Behavior

Using the command:
`inso generate config .\demo\target\openapi.json --output kong/kong1.yml --type declarative --tags "demo1"`

Path `/demo2/test` is converted to `/demo2/test$` instead of `/demo2/test`.

This breaks kong-spec-expose plugin for kong which listens for `/specz` at the end of any route path.

The problem is at: https://github.com/Kong/insomnia/blob/7a8510f89cb2f2e6b4ab3e25142554b01b320292/packages/openapi-2-kong/src/common.ts#L73

openapi.json:
```json
{
	"openapi": "3.0.1",
	"info": {
		"title": "springservicedemo2",
		"version": "1.2.3"
	},
	"servers": [
		{
			"url": "http://springservicedemo2:8080"
		}
	],
	"paths": {
		"/demo2/users/{id}": {
			"get": {
				"tags": [
					"UserApi"
				],
				"summary": "this is summary for getUser",
				"description": "Method to get the user",
				"operationId": "getUser",
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"description": "ID of the user to get",
						"required": true,
						"schema": {
							"type": "string"
						},
						"example": "u123"
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/UserDTO"
								}
							}
						}
					}
				}
			}
		},
		"/demo2/test": {
			"get": {
				"tags": [
					"hello-controller"
				],
				"operationId": "getHello",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"text/plain": {
								"schema": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"UserDTO": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"firstname": {
						"type": "string"
					},
					"lastname": {
						"type": "string"
					}
				}
			}
		}
	}
}
```

should convert to this:

```yaml
_format_version: "1.1"
services:
  - name: springservicedemo2
    protocol: http
    host: springservicedemo2
    port: 8080
    path: /
    plugins: []
    routes:
      - tags:
          - OAS3_import
          - OAS3file_openapi.json
          - demo2
        name: springservicedemo2-getUser
        methods:
          - GET
        paths:
          - /demo2/users/(?<id>[^\/\s]+)$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_openapi.json
          - demo2
        name: springservicedemo2-getHello
        methods:
          - GET
        paths:
          - /demo2/test
        strip_path: false
    tags:
      - OAS3_import
      - OAS3file_openapi.json
      - demo2
upstreams:
  - name: springservicedemo2
    targets:
      - target: springservicedemo2:8080
        tags:
          - OAS3_import
          - OAS3file_openapi.json
          - demo2
    tags:
      - OAS3_import
      - OAS3file_openapi.json
      - demo2
```

### Actual Behavior

instead what I get is this

```yaml
_format_version: "1.1"
services:
  - name: springservicedemo2
    protocol: http
    host: springservicedemo2
    port: 8080
    path: /
    plugins: []
    routes:
      - tags:
          - OAS3_import
          - OAS3file_openapi.json
          - demo2
        name: springservicedemo2-getUser
        methods:
          - GET
        paths:
          - /demo2/users/(?<id>[^\/\s]+)$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_openapi.json
          - demo2
        name: springservicedemo2-getHello
        methods:
          - GET
        paths:
          - /demo2/test$
        strip_path: false
    tags:
      - OAS3_import
      - OAS3file_openapi.json
      - demo2
upstreams:
  - name: springservicedemo2
    targets:
      - target: springservicedemo2:8080
        tags:
          - OAS3_import
          - OAS3file_openapi.json
          - demo2
    tags:
      - OAS3_import
      - OAS3file_openapi.json
      - demo2
```
