### ISSUE TITLE
SecuritySchemes does not inject issuer and scopes into openIdConnect Plugin with OpenAPI-2-Kong

### ISSUE THREAD

**Issue by dmortim** [getinsomnia/insomnia#4572]
### Expected Behavior

When using securitySchemes the scopes and the openIdConnectUrl should be injected into the Kong OpenIdConnect plugin configuration. 

### Actual Behavior

When using security schemas with x-kong-security element, the scopes and issuer are not applied to the routes and it results in a schema violation when applying the configuration.  

```
while processing event: {Update} plugin openid-connect for route XXXXX failed: HTTP status 400 (message: "schema violation (config.issuer: required field missing)")
```

### Reproduction Steps

``` yaml
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://idp-endpoint.example.com/.well-kown # This should be injected into the kong-plugin configuration as the issuer
      x-kong-security-openid-connect:
        config:
          auth_methods:
            - bearer
        enabled: true
        protocols:
        - http
        - https

paths:
  /example/path:
    get:
      security:
        - openId:
            - example-scope # This should be injected into the kong-plugin configuration as the scopes required
``` 

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It seems this occurs because of this line. The plugin configuration is replacing the security configuration. 

https://github.com/Kong/insomnia/blob/develop/packages/openapi-2-kong/src/declarative-config/security-plugins.ts#L114

### Insomnia Version

2.4.1

### What operating system are you using?

Other Linux

### Operating System Version

redhat

### Installation method

binary
