### ISSUE TITLE
inso lint cannot run against custom spectral ruleset with "excepts" including paths

### ISSUE THREAD

**Issue by TiMESPLiNTER** [getinsomnia/insomnia#6155]
### Expected Behavior

It lints and respects the `excepts` section in the custom ruleset.

### Actual Behavior

It fails with:

> FATAL  Document must have some source assigned. If you use Spectral programmatically make sure to pass the source to Document

### Reproduction Steps

By copyting this spectral ruleset file in the same folder as the openapi.yaml file, you can produce the error:

```yaml
extends: spectral:oas

except:
  "./openapi.yaml#/paths/~1v1~1cars/post/responses/202/content/application~1json/examples":
    - oas3-valid-media-example

```

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

3.17.0

### What operating system are you using?

Other Linux

### Operating System Version

Docker Alpine

### Installation method

docker image
