### ISSUE TITLE
Single server in API spec does not generate an Upstream in the Kong Configuration File.

### ISSUE THREAD

**Issue by fv316** [getinsomnia/insomnia#6421]
### Expected Behavior

```
openapi: 3.0.0
info:
  title: Sample
  version: '1.0'
servers:
  - url: 'https://production.sample.com/api'
paths:
  /v2/things:
    get:
      summary: List things
      operationId: operationId
      responses:
        '200':
          description: Working

```

This API spec with the `inso generate config apispec.yaml --kongVersion 3` should generate

```
_format_version: "3.0"
services:
  - name: Sample
    protocol: https
    host: Sample.upstream
    port: 443
    path: /api
    plugins: []
    routes:
      - tags: &a1
          - OAS3_import
          - OAS3file_open-api.yaml
        name: Sample-operationId
        methods:
          - GET
        paths:
          - ~/v2/things$
        strip_path: false
    tags: *a1
upstreams:
  - name: Sample.upstream
    targets:
      - target: production.sample.com:443
        tags: *a1
    tags: *a1
```

### Actual Behavior

Instead, this is generated: 

```
_format_version: "3.0"
services:
  - name: Sample
    protocol: https
    host: production.sample.com
    port: 443
    path: /api
    plugins: []
    routes:
      - tags: &a1
          - OAS3_import
          - OAS3file_open-api.yaml
        name: Sample-operationId
        methods:
          - GET
        paths:
          - ~/v2/things$
        strip_path: false
    tags: *a1

```

### Reproduction Steps

1. Copy the sample apispec.yaml file in the example
2. Run the command `inso generate config apispec.yaml --kongVersion 3`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

According to the readme:

> One OpenAPI spec will result in one `service` and one `upstream`, and each individual `server` in the root `servers` property will become a `target` in the `upstream`.

However, when the openAPI.yaml only has one server, the upstream is not generated. Instead, the server URL is directly loaded into the host in the Kong configuration file.

I believe the issue is that the `hasUpstreams` function will only return true if more than 1 upstream is present. However, according to the readme, upstreams should be generated even when there is only 1 server (this is relevant because the behaviour of having an upstream versus a hardcoded host name for Kong is different).

```
    if (hasUpstreams(api)) {
      document.upstreams = generateUpstreams(api, tags);
    }
```

### Insomnia Version

2023.5.6

### What operating system are you using?

macOS

### Operating System Version

Darwin Kernel Version 22.3.0

### Installation method

homebrew
