### ISSUE TITLE
CSS mistake attr (wide)

### ISSUE THREAD

**Issue by MrFiregore** [getinsomnia/insomnia#6969]
CSS mistake attr (wide) in this file:

https://github.com/Kong/insomnia/blob/ac03fb439b3627c053e58f9ce6b213e6305c41b2/packages/insomnia/src/ui/css/main.css#L2467

could be this instead?
```css
.modal.modal--wide .modal__content__wrapper {
  width: var(--modal-width-wide) ;
}
```
