### ISSUE TITLE
export of scratchpad leaked private environments

### ISSUE THREAD

**Issue by xenoterracide** [getinsomnia/insomnia#8506]
### Expected Behavior

export and clicking no for private environments should not include private environments.

### Actual Behavior

it would appear that whether you click yes or no is a noop. Either way my private environment got exported

```yml
  subEnvironments:
    - name: QA
      meta:
        id: env_1be88a2c73d64ef4a619f87f1f9c2e40
        created: 1742321591999
        modified: 1742324167037
        isPrivate: true
        sortKey: 1742321591999
      data:
        client_id: realcredential
```

### Reproduction Steps

1. have a private sub environment
2. click scratchpad
3. click export
4. click insomnia 5
5. Do you want to include private environments in your export?

either yes or no to step 5 produces the same result

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [x] Local only

### Insomnia Version

11.0.0

### What operating system are you using?

macOS

### Operating System Version

Darwin 603e5f60b5a8 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6031 arm64 arm Darwin

### Installation method

download from insomnia.rest
