### ISSUE TITLE
Parsing between insomnia template V4 and V5 has a problem.

### ISSUE THREAD

**Issue by wangmir** [getinsomnia/insomnia#8529]
### Expected Behavior

Import V4 collection to 11.0.0 insomnia, and export it to V5.
And then import that template to insomnia.

It should be imported correctly.

### Actual Behavior

Import results in parsing error.

### Reproduction Steps

1. create a collection
2. add header with no option.
3. export it
4. re-import it

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [x] Local only

### Additional Information

There is a bug on parsing V4 and V5.

I tried to import collection using V4 json syntax, and I exported it as a yaml file again.
After that, when I try to import yaml file again, some of collection was not able to be imported.

I narrowed down the root cause, and I finally found that this is because of header option.

![Image](https://github.com/user-attachments/assets/8ac5b6ee-e4cd-4ccf-aea4-2ee13b75274a)

Please check last header option in the image. When there is a header which is not defined, we can keep this, and still there was no problem on sending request, and storing this before. 

But from the V5, the syntax for this changed like :

![Image](https://github.com/user-attachments/assets/81199c46-cfb8-4e78-9674-5e209cdf57ab)

And this results in parsing failure.

### Insomnia Version

11.0.0

### What operating system are you using?

macOS

### Operating System Version

15.3.2

### Installation method

downloaded from insomnia.rest

**Comment by gatzjames** [comment]
Hey @wangmir can you try the v11.0.1 patch and let us know if the issue is resolved for you?

**Comment by wangmir** [comment]
@gatzjames it is not fixed from v11.0.1

**Comment by wangmir** [comment]
@gatzjames And, can we have more informative error message than 

![Image](https://github.com/user-attachments/assets/20ebd3cb-76e3-4e0d-952d-35bcff06f289)

Because, I cannot recognize what is real error from here.

**Comment by wangmir** [comment]
@gatzjames Any update on this? I additionally found that multi-part request is not correctly parsed from the template too.

**Comment by wangmir** [comment]
```yaml
        children:
          - url: "{{ _.base_url }}/url"
            name: file upload 
            meta:
              id: req_96703a814eeb436e95ffeb7c61f9ac10
              created: 1693894788962
              modified: 1693894788962
              isPrivate: false
              sortKey: -1601686620438.8125
            method: POST
            body:
              mimeType: multipart/form-data
              params:
                - name: file_data
                  fileName: /home/ID/file_name.file
                  type: file
                  id: pair_4d52bc536e134e17a4bdb88cf131f700
```

In this case, when `params` is there, it is failing on parsing. When I remove it, parsing itself was fine, but it was parsed as `WS` rather than multi-part request.

**Comment by sygecom** [comment]
Same error still in version 11.0.2

![Image](https://github.com/user-attachments/assets/10a8038c-8171-4ce0-8d97-68b4a878b9e1)

**Comment by gatzjames** [comment]
Hey @wangmir thanks for the feedback.
I will post here when we have a beta with the fix if you can help us verify it

**Comment by gatzjames** [comment]
Hey @wangmir could you try the latest beta and let us know if it fixes it for you [11.1.0-beta.0](https://github.com/Kong/insomnia/releases/tag/core%4011.1.0-beta.0)?

**Comment by wangmir** [comment]
@gatzjames I tested it, and some of the issues are fixed, but not all.

I erased confidential details, but the structure itself is same.

```yaml
          - url: "{{ _.base_url }}{{ _.graphql_path }}"
            name: Test
            meta:
              id: req_8e23285c508247408f61c3dc8ad972e5
              created: 1717338887649
              modified: 1717338887649
              isPrivate: false
              sortKey: -1693445323581
            method: POST
            body:
              mimeType: multipart/form-data
              params:
                - name: operations
                  value: >-
                    {
                    	"query": "mutation { 

                    }
                  id: pair_1a533639d5204abb9274ea9c0f3c5955
                  type: text
                  multiline: true
                - id: pair_16d13ffd2da14fc28acd09cb081030b9
                  name: map
                  value: |-
                    {
                      "0": ["variables.p"],
                    	"1": ["variables.k"]
                    }
                  type: text
                  multiline: true
                - id: pair_45da67a9ebc245e28a2d3a1a8a720ac6
                  name: "0"
                  type: file
                  fileName: /temp/t
                - id: pair_0ddfc64c93134087bd41f0669236974c
                  name: "1"
                  type: file
                  fileName: /temp/t
            headers:
              - name: Content-Type
                value: multipart/form-data
                id: pair_4d3c255cdfd64ae598ef469c56950085
            authentication:
              type: basic
              useISO88591: false
              disabled: false
              username: "{{ _.auth_email }}"
              password: "{{ _.auth_password }}"
            settings:
              renderRequestBody: true
              encodeUrl: true
              followRedirects: global
              cookies:
                send: true
                store: true
              rebuildPath: false
```

And I found the reason. In case of other, `multiline` was like `text/plain`, but in this template it was like `multiline: true`.
