### ISSUE TITLE
[Development] Dynamically link libcurl for Linux dev

### ISSUE THREAD

**Issue by samuelcecilio** [getinsomnia/insomnia#967]
- Insomnia Version: 5.16.6
- Operating System: Solus 3.999 (linux 4.16.13-74 / node 8.11.2)

Solus repository has version 5.14.7, I would like to upgrade to 5.16.6. However, I get the following error:

````bash
lerna ERR! node-pre-gyp verb command install []
lerna ERR! node-pre-gyp info check checked for "/home/build/YPKG/root/insomnia/build/insomnia-5.16.6/packages/insomnia-libcurl/node_modules/insomnia-node-libcurl/lib/binding/node_libcurl.node" (not found)
lerna ERR! node-pre-gyp http GET https://github.com/getinsomnia/node-libcurl/releases/download/v1.2.17/node_libcurl-v1.2.17-node-v57-linux-x64.tar.gz
lerna ERR! node-pre-gyp http 404 https://github.com/getinsomnia/node-libcurl/releases/download/v1.2.17/node_libcurl-v1.2.17-node-v57-linux-x64.tar.gz
lerna ERR! node-pre-gyp ERR! Tried to download(404): https://github.com/getinsomnia/node-libcurl/releases/download/v1.2.17/node_libcurl-v1.2.17-node-v57-linux-x64.tar.gz 
lerna ERR! node-pre-gyp ERR! Pre-built binaries not found for insomnia-node-libcurl@1.2.17 and node@8.11.2 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
lerna ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/getinsomnia/node-libcurl/releases/download/v1.2.17/node_libcurl-v1.2.17-node-v57-linux-x64.tar.gz 
lerna ERR! node-pre-gyp verb command build [ 'rebuild' ]
lerna ERR! Could not run curl-config, please make sure libcurl dev package is installed.
lerna ERR! Output: curl was built with static libraries disabled
````

Is it possible to reverse libcurl static link? What is my best option?

_Note: I'm not a Solus developer. I want to update Insomnia because I use it in my daily work._

**Comment by samuelcecilio** [comment]
build:

````bash
npm install electron-builder
export PATH=$PATH:$workdir/node_modules/.bin
npm run bootstrap
npm run app-build
cd packages/insomnia-app/build
electron-builder --linux dir --x64
````

install:

````bash
install -Dm644 packages/insomnia-app/app/static/icon.png $installdir/usr/share/pixmaps/insomnia.png
install -Dm644 $pkgfiles/insomnia.desktop $installdir/usr/share/applications/insomnia.desktop
install -dm00644 $installdir/usr/share/insomnia
install -dm00644 $installdir/usr/bin
cp -R packages/insomnia-app/build/dist/linux-unpacked/* $installdir/usr/share/insomnia/
ln -s /usr/share/insomnia/insomnia $installdir/usr/bin/insomnia
````

builddeps:

````
pkgconfig(alsa)
pkgconfig(gconf-2.0)
pkgconfig(gtk+-2.0)
pkgconfig(libcurl)
pkgconfig(xscrnsaver)
pkgconfig(xtst)
cups-devel
lerna
nodejs
````

rundeps:

````
nodejs
````

**Comment by gschier** [comment]
Hmm, I'm not sure what Solus so pardon my ignorance, but could you run one of the pre-packaged builds?

https://github.com/getinsomnia/insomnia/releases/download/v5.16.6/insomnia-5.16.6-x86_64.AppImage
https://github.com/getinsomnia/insomnia/releases/download/v5.16.6/insomnia-5.16.6.tar.gz
https://github.com/getinsomnia/insomnia/releases/download/v5.16.6/insomnia_5.16.6_amd64.snap

Having said that, I do need do implement dynamically-linked build for development on Linux. The switch to a static build was a rather sudden decision so I have yet to get around to fixing it yet. I'll see if I can figure something out soon.

**Comment by samuelcecilio** [comment]
I'm using AppImage. Works well, thanks.

> Solus uses the `eopkg` package management system to deliver software to the end-user.

[Home | Solus](https://solus-project.com/home/)

With the `insomnia-5.16.6.tar.gz` file, I can use `solbuild` to package the application in `.eopkg` format and distribute it in _Solus Software Center_

Dynamically-linked would be great.

As an example, I would use the following `package.yml` to generate the `.eopkg` file:

````yml
name       : insomnia
version    : 5.16.6
release    : 3
source     :
    - https://github.com/getinsomnia/insomnia/archive/v5.16.6.tar.gz : 2409aa6e340ba197953b9748c20fd09d66958659238f034bd50311b4ad01e45a
license    : AGPL-3.0
component  : programming.tools
summary    : Insomnia is a cross-platform REST client
description: |
    Insomnia is a cross-platform REST client
networking : yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
    - lerna
    - nodejs
rundeps    :
    - nodejs
build      : |
    ...
install    : |
    ...
````
